// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WDaslnwHXShuSE1L29VrLkHvj0GR4JA',
    appId: '1:438972631338:web:571daa8e038eedd244f653',
    messagingSenderId: '438972631338',
    projectId: 'tybatest-9e884',
    authDomain: 'tybatest-9e884.firebaseapp.com',
    storageBucket: 'tybatest-9e884.appspot.com',
    measurementId: 'G-ZH220XJV6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvx0klHpfcaQRBIga4hA9WAGDc9HFgSlE',
    appId: '1:438972631338:android:417307770efe1e1e44f653',
    messagingSenderId: '438972631338',
    projectId: 'tybatest-9e884',
    storageBucket: 'tybatest-9e884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJckC64Qfar8huID86YoJBywI7fbfIfA',
    appId: '1:438972631338:ios:3c2ac25176fac0f944f653',
    messagingSenderId: '438972631338',
    projectId: 'tybatest-9e884',
    storageBucket: 'tybatest-9e884.appspot.com',
    iosClientId: '438972631338-ai6g2vgmhfvnif4eb959ais1sb68snk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJckC64Qfar8huID86YoJBywI7fbfIfA',
    appId: '1:438972631338:ios:ba2650676b0c7e3e44f653',
    messagingSenderId: '438972631338',
    projectId: 'tybatest-9e884',
    storageBucket: 'tybatest-9e884.appspot.com',
    iosClientId: '438972631338-1p4sdsthb7fpun811b13a4tg00ibm53e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1ios',
  );
}
